service: serverless-test
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-west-2
  httpApi: 
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:GetItem
          Resource: '*'
        - Effect: Allow
          Action: dynamodb:PutItem
          Resource: "*"
        - Effect: Allow
          Action: dynamodb:UpdateItem
          Resource: "*"

functions:
  hello:
    handler: endpoints/handlers.hello
    events:
      - httpApi:
          path: /
          method: get
  fetchChargeDevice:
    handler: endpoints/fetchChargeDevice/lambda.handler
    events:
      - httpApi:
          path: /api/chargeDevices/{chargeDeviceId}
          method: get

  putChargeDevice:
    handler: endpoints/putChargeDevice/lambda.handler
    events: 
      - httpApi:
          path: /api/chargeDevices
          method: put

  charge:
    handler: endpoints/charge/lambda.handler
    events:
     - httpApi:
          path: /api/chargeDevices/{chargeDeviceId}/charge
          method: patch

resources:
  Resources:
    Reports:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Reports
        AttributeDefinitions:
          - AttributeName: reportId
            AttributeType: S
        KeySchema:
          - AttributeName: reportId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ChargeDevices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ChargeDevices
        AttributeDefinitions:
          - AttributeName: chargeDeviceId
            AttributeType: S
        KeySchema:
          - AttributeName: chargeDeviceId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 20
          WriteCapacityUnits: 20
    Users:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Users
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
	
custom:
  serverless-offline:
    httpPort: 3100

plugins:
  - serverless-plugin-typescript
  - serverless-offline